# Generated by Django 4.2.1 on 2023-11-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
    ]
