# Generated by Django 4.2.1 on 2023-11-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_is_lost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_lost',
        ),
    ]
